# Generated by Django 3.0.8 on 2020-07-07 10:00

import ckeditor.fields
import django.contrib.postgres.fields
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
                ('publish_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_header', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='web/media/'), upload_to='')),
                ('blog_content', ckeditor.fields.RichTextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Entry',
                'verbose_name_plural': 'Blog Entries',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CarouselCaption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('publish_date', models.DateField(auto_now=True)),
                ('caption_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarouselCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=10)),
                ('cover', models.ImageField(upload_to='backgrounds')),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('slide', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(max_length=100)),
                ('picture', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='web/media/'), upload_to='')),
                ('picture_url', models.URLField(blank=True, max_length=100)),
                ('picture_no', models.IntegerField(blank=True, unique=True)),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioGraphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('graphic', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='web/media/'), upload_to='')),
                ('site_url', models.URLField(max_length=100)),
                ('graphic_no', models.IntegerField(unique=True)),
                ('graphic_category', models.CharField(max_length=100)),
                ('category_icon', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_icon', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('skill_desc', models.CharField(max_length=150)),
                ('experienced', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('written', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
