# Generated by Django 3.0.8 on 2020-07-07 11:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='web/media/'), upload_to=''),
        ),
    ]
